# Generated by Django 3.1.7 on 2021-04-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_auto_20210412_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mp3',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mp4',
            name='title',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_group_parent',
            field=models.BooleanField(default=True),
        ),
    ]
