# Generated by Django 3.1.7 on 2021-03-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0004_auto_20210320_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newAccount',
            field=models.BooleanField(default=True),
        ),
    ]
