# Generated by Django 3.1.7 on 2021-03-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0006_spotifytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
