# Generated by Django 3.1.7 on 2021-04-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0003_mp3'),
        ('karaoke', '0007_friendrequest_is_active'),
    ]

    operations = [
    ]
