# Generated by Django 3.1.7 on 2021-04-10 22:19

from django.db import migrations, models
import karaoke.models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0008_merge_20210405_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='MP4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to='', validators=[karaoke.models.MP4.validate_video_file])),
            ],
        ),
        migrations.AlterField(
            model_name='mp3',
            name='song',
            field=models.FileField(upload_to='', validators=[karaoke.models.MP3.validate_audio_file]),
        ),
    ]
